config/routes.rb
require 'subdomain'

Kassi::Application.routes.draw do

  
  scope "(/:locale)" do
    devise_for :people, :controllers => { :confirmations => "confirmations" }
    
    namespace :admin do
      resources :feedbacks
    end
    resources :listings do
      collection do
        get :more_listings
        get :browse
        get :random
      end
      resources :images, :controller => :listing_images
      resources :comments
    end
    resources :people do
      collection do
        get :check_username_availability
        get :check_email_availability
        get :check_invitation_code
        get :not_member
      end
      member do 
        put :update_avatar
        put :activate
        put :deactivate
      end
      resources :listings do
        member do 
          put :close
        end  
      end  
      resources :messages, :controller => :conversations do 
        collection do
          get :received
          get :sent
          get :notifications
        end
        member do
          put :accept
          put :reject
          put :cancel
        end
        resources :messages
        resources :feedbacks, :controller => :testimonials do
          collection do
            put :skip
          end  
        end    
      end
      resource :settings do
        member do
          get :profile
          get :avatar
          get :account
          get :notifications
        end
      end
      resources :badges
      resources :testimonials
    end
    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :register_details
      end  
    end
    resource :terms do
      member do
        post :accept
      end  
    end    
    resources :sessions do
      collection do
        post :request_new_password
      end
    end  
    resources :consent
    resource :sms do
      get :message_arrived
    end
    resources :contact_requests do
      collection do
        get :thank_you
      end
    end
  end
  
  match '/badges/:style/:id.:format' => "badges#image"
  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/:locale/load" => "listings#load", :as => :load
  match "/:locale/loadmap" => "listings#loadmap", :as => :loadmap
  match "/:locale/offers" => "listings#offers", :as => :offers
  match "/:locale/requests" => "listings#requests", :as => :requests
  match "/:locale/offers/tag/:tag" => "listings#offers", :as => :offers_with_tag
  match "/:locale/requests/tag/:tag" => "listings#requests", :as => :requests_with_tag
  match "/:locale/people/:id/:type" => "people#show", :as => :person_listings
  match "/:locale/people/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation
  match "/:locale/people/:person_id/messages" => "conversations#received", :as => :reply_to_listing
  match "/:locale/listings/:id/reply" => "conversations#new", :as => :reply_to_listing
  match "/:locale/listings/new/:type/:category" => "listings#new", :as => :new_request_category
  match "/:locale/listings/new/:type" => "listings#new", :as => :new_request
  match "/:locale/search" => "search#show", :as => :search
  match "/:locale/logout" => "sessions#destroy", :as => :logout, :method => :delete
  match "/:locale/signup" => "people#new", :as => :sign_up
  match "/:locale/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
  match "/:locale/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
  match "/:locale/login" => "sessions#new", :as => :login
  match "/change_locale" => "i18n#change_locale"
  match '/:locale/tag_cloud' => "tag_cloud#index", :as => :tag_cloud
  match "/:locale/offers/map/" => "listings#offers_on_map", :as => :offers_on_map
  match "/:locale/requests/map/" => "listings#requests_on_map", :as => :requests_on_map
  match "/api/query" => "listings#serve_listing_data", :as => :listings_data
  match "/:locale/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
  match "/:locale/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
  
  constraints(Subdomain) do
    match '/:locale/' => 'homepage#index'
    match '/' => 'homepage#index'
  end  
  
  match '/:locale' => 'dashboard#index'
  
  root :to => 'dashboard#index'
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_filter :save_current_path, :only => :show
  before_filter :ensure_authorized_to_view, :only => :show

  before_filter :only => [ :new, :create ] do |controller|
    controller.ensure_logged_in(["you_must_log_in_to_create_new_#{params[:type]}", "create_one_here".to_sym, sign_up_path])
  end
  
  before_filter :only => [ :edit, :update, :close ] do |controller|
    controller.ensure_logged_in "you_must_log_in_to_view_this_content"
  end
  
  before_filter :only => [ :close ] do |controller|
    controller.ensure_current_user_is_listing_author "only_listing_author_can_close_a_listing"
  end
  
  before_filter :only => [ :edit, :update ] do |controller|
    controller.ensure_current_user_is_listing_author "only_listing_author_can_edit_a_listing"
  end
  
  def index
    redirect_to root
  end
  
  def requests
    params[:listing_type] = "request"
    @to_render = {:action => :index}
    @listing_style = "listing"
    load
  end
  
  def offers
    params[:listing_type] = "offer"
    @to_render = {:action => :index}
    @listing_style = "listing"
    load
  end

  # detect the browser and return the approriate layout
  def detect_browser
    if APP_CONFIG.force_mobile_ui
        return true
    end
    
    mobile_browsers = ["android", "ipod", "opera mini", "blackberry", 
"palm","hiptop","avantgo","plucker", "xiino","blazer","elaine", "windows ce; ppc;", 
"windows ce; smartphone;","windows ce; iemobile", 
"up.browser","up.link","mmp","symbian","smartphone", 
"midp","wap","vodafone","o2","pocket","kindle", "mobile","pda","psp","treo"]
    if request.headers["HTTP_USER_AGENT"]
	    agent = request.headers["HTTP_USER_AGENT"].downcase
	    mobile_browsers.each do |m|
		    return true if agent.match(m)
	    end    
    end
    return false
  end
    

  # Used to load listings to be shown
  # How the results are rendered depends on 
  # the type of request and if @to_render is set
  def load
    @title = params[:listing_type]
    @tag = params[:tag]
    @to_render ||= {:partial => "listings/listed_listings"}
    @listings = Listing.open.order("created_at DESC").find_with(params, @current_user, @current_community).paginate(:per_page => 15, :page => params[:page])
    @request_path = request.fullpath
    if request.xhr? && params[:page] && params[:page].to_i > 1
      render :partial => "listings/additional_listings"
    else
      render @to_render
    end
  end 
  
  def loadmap
    @title = params[:listing_type]
    @listings = Listing.open.order("created_at DESC").find_with(params, @current_user)
    @listing_style = "map"
    @to_render ||= {:partial => "listings/listings_on_map"}
    @request_path = request.fullpath
    render  @to_render
  end

  # The following two are simple dummy implementations duplicating the
  # functionality of normal listing methods.
  def requests_on_map
    params[:listing_type] = "request"
    @to_render = {:action => :index}
    @listings = Listing.open.order("created_at DESC").find_with(params, @current_user, @current_community)
    @listing_style = "map"
    load
  end

  def offers_on_map
    params[:listing_type] = "offer"
    @to_render = {:action => :index}
    @listing_style = "map"
    load
  end
  
  
  # A (stub) method for serving Listing data (with locations) as JSON through AJAX-requests.
  def serve_listing_data
    @listings = Listing.open.joins(:origin_loc).group("listings.id").
                order("listings.created_at DESC").find_with(params, @current_user, @current_community).select("listings.id, listing_type, category, latitude, longitude")
    render :json => { :data => @listings }
  end
  
  def listing_bubble
    if params[:id]
      @listing = Listing.find(params[:id])
      if @listing.visible_to?(@current_user, @current_community)
        render :partial => "homepage/recent_listing", :locals => { :listing => @listing }
      else
        render :partial => "bubble_listing_not_visible"
      end
    end 
  end
  
  # Used to show multiple listings in one bubble
  def listing_bubble_multiple
    @listings = Listing.visible_to(@current_user, @current_community, params[:ids])
    if @listings.size > 0
      render :partial => "homepage/recent_listing", :collection => @listings, :as => :listing, :spacer_template => "homepage/request_spacer"
    else
      render :partial => "bubble_listing_not_visible"
    end
  end

  def show
    @listing.increment!(:times_viewed)
  end
  
  def new
    @listing = Listing.new
    @listing.listing_type = params[:type]
    @listing.category = params[:category] || "item"
    if @listing.category == "rideshare"
	    @listing.build_origin_loc(:location_type => "origin_loc")
	    @listing.build_destination_loc(:location_type => "destination_loc")
    else
	    if (@current_user.location != nil)
	      temp = @current_user.location
	      temp.location_type = "origin_loc"
	      @listing.build_origin_loc(temp.attributes)
      else
	      @listing.build_origin_loc(:location_type => "origin_loc")
      end
    end
    1.times { @listing.listing_images.build }
    respond_to do |format|
      format.html
      format.js {render :layout => false}
    end
  end
  
  def create
    if params[:listing][:origin_loc_attributes][:address].empty? || params[:listing][:origin_loc_attributes][:address].blank?
      params[:listing].delete("origin_loc_attributes")
    end
    @listing = @current_user.create_listing params[:listing]
    if @listing.new_record?
      1.times { @listing.listing_images.build } if @listing.listing_images.empty?
      render :action => :new
    else
      path = new_request_category_path(:type => @listing.listing_type, :category => @listing.category)
      flash[:notice] = ["#{@listing.listing_type}_created_successfully", "create_new_#{@listing.listing_type}".to_sym, path]
      Delayed::Job.enqueue(ListingCreatedJob.new(@listing.id, request.host))
      redirect_to @listing
    end
  end
  
  # def create
  #     if params[:listing][:origin_loc_attributes][:address].empty?
  #       params[:listing].delete("origin_loc_attributes")
  #     end
  #   @listing = @current_user.create_listing params[:listing]
  #   if @listing.category != "rideshare"
  #     @location = @listing.create_location(params[:location])
  #   else
  #     @origin_loc = @listing.create_origin_loc(params[:origin_loc])
  #     @destination_loc = @listing.create_destination_loc(params[:destination_loc])
  #   end
  #   if @listing.new_record?
  #     1.times { @listing.listing_images.build } if @listing.listing_images.empty?
  #     render :action => :new
  #   else
  #     path = new_request_category_path(:type => @listing.listing_type, :category => @listing.category)
  #     flash[:notice] = ["#{@listing.listing_type}_created_successfully", "create_new_#{@listing.listing_type}".to_sym, path]
  #     Delayed::Job.enqueue(ListingCreatedJob.new(@listing.id, request.host))
  #     redirect_to @listing
  #   end
  # end
  
  def edit
	  if !@listing.origin_loc
	      @listing.build_origin_loc(:location_type => "origin_loc")
	  end
    1.times { @listing.listing_images.build } if @listing.listing_images.empty?
  end
  
  def update
    if (params[:listing][:origin] && (params[:listing][:origin_loc_attributes][:address].empty? || params[:listing][:origin].blank?))
      params[:listing].delete("origin_loc_attributes")
      if @listing.origin_loc
        @listing.origin_loc.delete
      end
    end
    if @listing.update_fields(params[:listing])
      @listing.location.update_attributes(params[:location]) if @listing.location
      flash[:notice] = "#{@listing.listing_type}_updated_successfully"
      redirect_to @listing
    else
      render :action => :edit
    end    
  end
  
  def close
    @listing.update_attribute(:open, false)
    notice = "#{@listing.listing_type}_closed"
    respond_to do |format|
      format.html { 
        flash[:notice] = notice
        redirect_to @listing 
      }
      format.js {
        flash.now[:notice] = notice
        render :layout => false 
      }
    end
  end
  
  #shows a random listing from current community
  def random
    open_listings_ids = Listing.open.select("id").find_with(nil, @current_user, @current_community).all
    if open_listings_ids.empty?
      redirect_to root and return
      #render :action => :index and return
    end
    random_id = open_listings_ids[Kernel.rand(open_listings_ids.length)].id
    #redirect_to listing_path(random_id)
    @listing = Listing.find_by_id(random_id)
    render :action => :show
  end
  
  def ensure_current_user_is_listing_author(error_message)
    @listing = Listing.find(params[:id])
    return if current_user?(@listing.author) || @current_user.has_admin_rights_in?(@current_community)
    flash[:error] = error_message
    redirect_to @listing and return
  end
  
  private
  
  # Ensure that only users with appropriate visibility settings can view the listing
  def ensure_authorized_to_view
    @listing = Listing.find(params[:id])
    unless @listing.visible_to?(@current_user, @current_community)
      if @listing.visibility.eql?("everybody")
        # This situation occurs when the user tries to access a listing
        # via a different community url.
        flash[:error] = "this_content_is_not_available_in_this_community"
        redirect_to root and return
      elsif @current_user
        flash[:error] = "you_are_not_authorized_to_view_this_content"
        redirect_to root and return
      else
        session[:return_to] = request.fullpath
        flash[:warning] = "you_must_log_in_to_view_this_content"
        redirect_to new_session_path and return
      end
    end
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
  
  # Class is selected if conversation type is currently selected
  def get_map_tab_class(tab_name)
    current_tab_name = action_name || "map_view"
    "inbox_tab_#{current_tab_name.eql?(tab_name) ? 'selected' : 'unselected'}"
  end
  
  # Class is selected if listing type is currently selected
  def get_new_listing_tab_class(listing_type)
    "new_listing_form_tab_#{@listing.listing_type.eql?(listing_type) ? 'selected' : 'unselected'}"
  end
  
  # Class is selected if category is currently selected
  def get_type_select_icon_class(category)
    "listing_type_select_icon_#{@listing.category.eql?(category) ? 'selected' : 'unselected'}_#{category}"
  end
  
  # The classes the checkbox gets depend on to which categories its' share type belongs to.
  def get_share_type_checkbox_classes(share_type)
    classes = ""
    Listing::VALID_CATEGORIES.each do |category|
      if Listing::VALID_SHARE_TYPES[@listing.listing_type][category] &&
         Listing::VALID_SHARE_TYPES[@listing.listing_type][category].include?(share_type)
        classes += "#{category} "
      end  
    end
    classes  
  end
  
  # Removes extra characters from datetime_select field
  def clear_datetime_select(&block)
    time = "</div><div class='date_select_time_container'><div class='datetime_select_time_label'>#{t('.at')}:</div>"
    colon = "</div><div class='date_select_time_container'><div class='datetime_select_colon_label'>:</div>"
    haml_concat capture_haml(&block).gsub(":", "#{colon}").gsub("&mdash;", "#{time}").gsub("\n", '')
  end
  
  # Class is selected if listing type is currently selected
  def get_listing_tab_class(tab_name)
    current_tab_name = params[:type] || "list_view"
    "inbox_tab_#{current_tab_name.eql?(tab_name) ? 'selected' : 'unselected'}"
  end
  
  def share_type_checkbox_checked?(share_type)
    if @listing.new_record?
      params[:share_type].eql?(share_type) || (@listing.default_share_type?(share_type) && !params[:share_type])
    else  
      @listing.has_share_type?(share_type)
    end  
  end
  
  def visibility_array
    array = []
    Listing::VALID_VISIBILITIES.each do |visibility|
      if visibility.eql?("this_community")
        array << [t(".#{visibility}", :community => @current_community.name), visibility]
      else
        array << [t(".#{visibility}"), visibility]
      end
    end
    return array  
  end
  
end

app/views/listings/_additional_listings.haml
= render :partial => "listings/listing_spacer" unless @listings.empty?
= render :partial => "listings/listed_listing", :collection => @listings, :as => :listing, :spacer_template => "listings/listing_spacer"

app/views/listings/_comment_form.haml
- if @listing.closed?
  = t(".you_cannot_send_a_new_comment_because_#{@listing.listing_type}_is_closed")  
- elsif logged_in?
  #comment_form
    = form_for Comment.new, :url => listing_comments_path(:listing_id => @listing.id.to_s), :remote => true do |f|
      .message_form_field_container
        = f.label :content, t(".write_comment")
      .message_form_field_container  
        = f.text_area :content
      .message_form_field_container
        = f.hidden_field :listing_id, :value => @listing.id.to_s
        = f.hidden_field :author_id, :value => @current_user.id
        = f.submit t(".send_comment"), :class => "send_button"
- else
  = t(".you_must")
  = link_to t(".log_in"), login_path
  = t(".to_send_a_comment")

app/views/listings/_destination.haml
.destination
= fields_for :destination_loc do |loc|
  = loc.hidden_field :address, :value => destination_loc.address
  = loc.hidden_field :google_address, :value => destination_loc.google_address
  = loc.hidden_field :latitude, :value => destination_loc.latitude
  = loc.hidden_field :longitude, :value => destination_loc.longitude
  = loc.hidden_field :location_type, :value => destination_loc.location_type

app/views/listings/_edit_links.haml
- if @listing.closed?
  = link_to t(".reopen_#{@listing.listing_type}"), edit_listing_path(@listing), :class => "edit_listing"
- else   
  = link_to t(".edit_#{@listing.listing_type}"), edit_listing_path(@listing), :class => "edit_listing"
  = link_to t(".close_#{@listing.listing_type}"), close_person_listing_path(@current_user, @listing), :class => "close_listing", :method => :put, :remote => true

app/views/listings/_googlemap.haml
.googlemap
  .jsmap{:id => "map_canvas", :style => "width: 250px; height: 200px"}
  :javascript 
    $(document).ready(function() { 
      if (!#{rideshare}){
        //var prefix = "listing_origin_loc_attributes";
        googlemapMarkerInit('map_canvas',"origin_loc");
      } else {
        googlemapRouteInit('map_canvas');
        showRoute(document.getElementById("origin_loc_google_address").value, document.getElementById("destination_loc_google_address").value)
      }
    });

app/views/listings/_help_texts.haml
.hidden_description{:id => "#{field}"}
  .hidden_title
    = t(".#{field}_title")
  .close_link
    = link_to "X", "#", :id => "close_x", :class => "close"
  .hidden_content
    = render :partial => "listings/help_texts/#{field}"

app/views/listings/_listed_listing_edit_links.haml
- unless current_user?(listing.author)
  = link_to t("listings.link_labels.link_label_for_#{listing.category}_#{listing.listing_type}"), reply_to_listing_path(:id => listing.id)
  &nbsp;|&nbsp;
- comment_count = listing.comments.count > 1 ? " (#{listing.comments.count})" : ""
= link_to "#{t('listings.please_comment')}#{comment_count}", listing_path(listing)+ "#comment_form"
- if current_user?(listing.author)
  &nbsp;|&nbsp;
  - if listing.closed?
    = link_to t("listings.edit_links.reopen_#{listing.listing_type}"), edit_listing_path(:id => listing.id)
  - else
    = link_to t("listings.listed_listing.edit"), edit_listing_path(:id => listing.id)
    &nbsp;|&nbsp;
    = link_to t("listings.edit_links.close_#{listing.listing_type}"), close_person_listing_path(@current_user, listing), :method => :put, :remote => true
  
  

app/views/listings/_listed_listings.haml
- if @listings.size > 0
  = render :partial => "listings/listed_listing", :collection => @listings, :as => :listing, :spacer_template => "listings/listing_spacer"
  = pageless(@listings.total_pages, '#search_results', @request_path, t(".loading_more_#{@title}s"))
- else
  #no_listings_found
    - if params[:listing_type]
      = t(".no_#{params[:listing_type]}s_with_the_conditions_you_gave")
      = link_to t(".#{Listing.opposite_type(params[:listing_type])}_something"), new_request_path(:type => Listing.opposite_type(params[:listing_type]))
    

app/views/listings/_listing_spacer.haml
.listing_spacer

app/views/listings/_origin.haml
.origin
= fields_for :origin_loc do |loc|
  = loc.hidden_field :address, :value => origin_loc.address
  = loc.hidden_field :google_address, :value => origin_loc.google_address
  = loc.hidden_field :latitude, :value => origin_loc.latitude
  = loc.hidden_field :longitude, :value => origin_loc.longitude
  = loc.hidden_field :location_type, :value => origin_loc.location_type

app/views/listings/close.js.erb
/* Display notice */
$("#notification_container").html("<%= escape_javascript(render(:partial => 'layouts/notifications')) %>");

/* Update status link */
$("#listing_reply_link").html("<%= escape_javascript(render(:partial => 'listings/reply_link')) %>");

/* Update edit links */
$("#edit_links").html("<%= escape_javascript(render(:partial => 'listings/edit_links')) %>");

/* Update comment form */
$("#comment_form").html("<%= escape_javascript(render(:partial => 'listings/comment_form')) %>");

/* Update listed listing closed status */
$("#listed_listing_closed_status_container_<%= @listing.id.to_s %>").html("<%= escape_javascript(render(:partial => 'listings/listed_listing_closed_status', :locals => { :listing => @listing })) %>");

/* Update listed listing closed status */
$("#listed_listing_edit_links_<%= @listing.id.to_s %>").html("<%= escape_javascript(render(:partial => 'listings/listed_listing_edit_links', :locals => { :listing => @listing })) %>");

app/views/listings/index.haml
- content_for :javascript do
  initialize_browse_view('#{@title}','#{@listing_style}','#{I18n.locale}');

#browse_page.grid_24
  .grid_6.alpha
    %h1= t(".#{@title}s")
    #left_link_panel_browse
      .left_panel_section
        .left_panel_title
          %h3= t(".category")
        = link_to t(".all_categories"), "#", :class => "selected", :name => "categories_all"
        = render :partial => "left_panel_link", :collection => Listing::VALID_CATEGORIES, :as => :title, :locals => { :type => "categories" }
      .left_panel_section
        .left_panel_title
          %h3= t(".#{params[:listing_type]}_type")
        = link_to t(".all_#{params[:listing_type]}_types"), "#", :class => "selected", :name => "sharetypes_all"
        = render :partial => "left_panel_link", :collection => Listing.unique_share_types(params[:listing_type]), :as => :title, :locals => { :type => "sharetypes" }
    -# Hidden temporarily.. = render :partial => "tag_cloud/tag_cloud", :locals => {:listing_type => params[:listing_type]}

  .grid_18.omega
    .grid_10.alpha
      #search_form_spacer
        &nbsp;
        
      .tabs.grid_9.alpha 
        .tabs.grid_9.alpha 
          #inbox_tabs
            %div{:class => get_map_tab_class(params[:listing_type]+ "s")} 
              - if params[:listing_type] == "request"
                = link_to t(".list_view"), requests_path
              - else
                = link_to t(".list_view"), offers_path            
            %div{:class => get_map_tab_class(params[:listing_type]+ "s_on_map")} 
              - if params[:listing_type] == "request" 
                = link_to t(".map_view"), requests_on_map_path, :name => "map_view"
              - else
                = link_to t(".map_view"), offers_on_map_path, :name => "map_view"
        
        .grid_3.omega
                          
    .grid_8.omega
      #new_listing_links
        = t(".did_not_found_what_you_were_looking_for")
        = link_to t(".request_something"), new_request_path(:type => "request")
        %br/
        = t(".you_have_something_others_do_not")
        = link_to t(".offer_something"), new_request_path(:type => "offer")
    .clear
    #profile_tab_spacer
      &nbsp;
    #search_results

      - if @listing_style == "listing"
        = render :partial => "listed_listings"
      - else
        = render :partial => "listings_on_map"
      

app/views/listings/new.js.erb
$('#listing_form_wrapper').html('<%= escape_javascript(render :partial => "listings/form/form_content") %>');

app/views/listings/show.haml
- content_for :javascript do
  initialize_comment_form('#{I18n.locale}');

- content_for :extra_javascript do
  = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true"

#listing_image_side.grid_8
  .image
    - if @listing.listing_images.empty?
      %div{:id => "listing_category_big_icon_#{@listing.category}"}
    - @listing.listing_images.each do |listing_image|
      = image_tag listing_image.image.url(:medium), :class => "listing_main_image", :alt => @listing.title
  - if current_user?(@listing.author) || (@current_user && @current_user.has_admin_rights_in?(@current_community))
    #edit_links
      = render :partial => "edit_links"
    
#listing_content_side.grid_16
  #listing_center.grid_9.alpha
    %h1
      #{t(".#{@listing.category}_#{@listing.listing_type}")}: #{@listing.title}
    - if @listing.category == "rideshare"
      %p
        %strong
          = t("listings.form.departure_time.departure_time") + ": " + l(@listing.valid_until, :format => :short)
    %p
      - text_with_line_breaks do
        = @listing.description.blank? ? t(".no_description") : @listing.description
    
    #share_types_and_tags
      - unless @listing.share_types.empty? && @listing.tag_list.empty?    
        - unless @listing.tag_list.empty?
          %strong
            = t(".tags") + ":"
          - @listing.tag_list.collect do |tag| 
            = tag + ((tag.eql?(@listing.tag_list.last)) ? "" : ", ")
        - unless @listing.share_types.empty? || @listing.tag_list.empty?
          %br/
        - unless @listing.share_types.empty?
          %strong
            = t(".share_types_#{@listing.listing_type}") + ":"
          - @listing.share_types.collect do |st| 
            = t("common.share_types.#{st.name}")  + ((st.name.eql?(@listing.share_types.last.name)) ? "" : ", ")
        - unless @listing.share_types.empty? && @listing.tag_list.empty?
          %br/
      %strong
        = t(".times_viewed") + ":"
      = pluralize(@listing.times_viewed.to_s, t(".time"), t(".times")) 
            
    #listing_author
      .float_left
        = small_avatar_thumb(@listing.author)
      #listing_author_description
        %strong
          = t(".#{@listing.listing_type}_author") + ":"
          = link_to @listing.author.name, @listing.author, :id => "listing_author_link"
        %br/
        %span{:class => "smaller"}
          = t(".#{@listing.listing_type}_created") + " " + l(@listing.created_at, :format => :short)

  #listing_right_panel.grid_7.omega
    #listing_reply_link
      = render :partial => "reply_link"
    - if @listing.origin_loc && @listing.origin_loc.address != ""
      #googlemap
        = render :partial => "googlemap", :locals => { :rideshare => (@listing.category == "rideshare")}
        = render :partial => "origin", :locals => { :origin_loc => @listing.origin_loc }
        - if @listing.category == "rideshare"
          = render :partial => "destination", :locals => { :destination_loc => @listing.destination_loc }
        - if @listing.location != nil 
          #single_listing_location
            = @listing.location.address
    #additional_listing_links
      .float_left
        = link_to(t(".share"), "http://twitter.com/share", :class => "twitter-share-button", "data-count" => "horizontal", "data-via" => "kassi_eu", "data-related" => "avoinyritys:Our company blog.")
        %script{:type => "text/javascript", :src => "http://platform.twitter.com/widgets.js"}
      .float_left
        = facebook_like
        - fb_image = @listing.listing_images.empty? ? "images/kassi_logo.png" : @listing.listing_images.first.image.url(:medium)
        - content_for :head do
          %meta{ :property => "og:title", :content => @listing.title} 
          %meta{ :property => "og:type", :content =>"website"}
          %meta{ :property => "og:url", :content =>"http://#{@current_community.domain}.#{request.domain}/listings/#{@listing.id.to_s}"}   
          %meta{ :property => "og:image", :content =>"http://#{@current_community.domain}.#{request.domain}/#{fb_image}"}
          %meta{ :property => "og:site_name", :content =>"Kassi: "}
          %meta{ :property => "fb:admins", :content =>"823616678"}
          %meta{ :property => "og:description", :content => @listing.content}
        
  .clear
  
  #comments
    %h2
      = image_tag "/images/icons/comment_icon.png"
      = t(".comments")
      %span{:id => "comment_count"}= "(#{@listing.comments.count})"
    = render :partial => "comment", :collection => @listing.comments
  
  #comment_notice  
  
  #listing_comment_form
    = render :partial => "comment_form"