config/routes.rb
require 'subdomain'

Kassi::Application.routes.draw do

  
  scope "(/:locale)" do
    devise_for :people, :controllers => { :confirmations => "confirmations" }
    
    namespace :admin do
      resources :feedbacks
    end
    resources :listings do
      collection do
        get :more_listings
        get :browse
        get :random
      end
      resources :images, :controller => :listing_images
      resources :comments
    end
    resources :people do
      collection do
        get :check_username_availability
        get :check_email_availability
        get :check_invitation_code
        get :not_member
      end
      member do 
        put :update_avatar
        put :activate
        put :deactivate
      end
      resources :listings do
        member do 
          put :close
        end  
      end  
      resources :messages, :controller => :conversations do 
        collection do
          get :received
          get :sent
          get :notifications
        end
        member do
          put :accept
          put :reject
          put :cancel
        end
        resources :messages
        resources :feedbacks, :controller => :testimonials do
          collection do
            put :skip
          end  
        end    
      end
      resource :settings do
        member do
          get :profile
          get :avatar
          get :account
          get :notifications
        end
      end
      resources :badges
      resources :testimonials
    end
    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :register_details
      end  
    end
    resource :terms do
      member do
        post :accept
      end  
    end    
    resources :sessions do
      collection do
        post :request_new_password
      end
    end  
    resources :consent
    resource :sms do
      get :message_arrived
    end
    resources :contact_requests do
      collection do
        get :thank_you
      end
    end
  end
  
  match '/badges/:style/:id.:format' => "badges#image"
  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/:locale/load" => "listings#load", :as => :load
  match "/:locale/loadmap" => "listings#loadmap", :as => :loadmap
  match "/:locale/offers" => "listings#offers", :as => :offers
  match "/:locale/requests" => "listings#requests", :as => :requests
  match "/:locale/offers/tag/:tag" => "listings#offers", :as => :offers_with_tag
  match "/:locale/requests/tag/:tag" => "listings#requests", :as => :requests_with_tag
  match "/:locale/people/:id/:type" => "people#show", :as => :person_listings
  match "/:locale/people/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation
  match "/:locale/people/:person_id/messages" => "conversations#received", :as => :reply_to_listing
  match "/:locale/listings/:id/reply" => "conversations#new", :as => :reply_to_listing
  match "/:locale/listings/new/:type/:category" => "listings#new", :as => :new_request_category
  match "/:locale/listings/new/:type" => "listings#new", :as => :new_request
  match "/:locale/search" => "search#show", :as => :search
  match "/:locale/logout" => "sessions#destroy", :as => :logout, :method => :delete
  match "/:locale/signup" => "people#new", :as => :sign_up
  match "/:locale/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
  match "/:locale/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
  match "/:locale/login" => "sessions#new", :as => :login
  match "/change_locale" => "i18n#change_locale"
  match '/:locale/tag_cloud' => "tag_cloud#index", :as => :tag_cloud
  match "/:locale/offers/map/" => "listings#offers_on_map", :as => :offers_on_map
  match "/:locale/requests/map/" => "listings#requests_on_map", :as => :requests_on_map
  match "/api/query" => "listings#serve_listing_data", :as => :listings_data
  match "/:locale/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
  match "/:locale/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
  
  constraints(Subdomain) do
    match '/:locale/' => 'homepage#index'
    match '/' => 'homepage#index'
  end  
  
  match '/:locale' => 'dashboard#index'
  
  root :to => 'dashboard#index'
  
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  belongs_to :listing
  
  has_many :messages, :dependent => :destroy 
  
  has_many :participations, :dependent => :destroy
  has_many :participants, :through => :participations, :source => :person
  
  VALID_STATUSES = ["pending", "accepted", "rejected"]
  
  validates_length_of :title, :in => 1..100, :allow_nil => false
  validates_inclusion_of :status, :in => VALID_STATUSES
  
  def self.unread_count(person_id)
    Conversation.scoped.
    joins(:participations).
    joins(:listing).
    where("(participations.is_read = '0' OR (conversations.status = 'pending' AND listings.author_id = '#{person_id}')) AND participations.person_id = '#{person_id}'").
    count
  end
  
  # Creates a new message to the conversation
  def message_attributes=(attributes)
    messages.build(attributes)
  end
  
  # Sets the participants of the conversation
  def conversation_participants=(conversation_participants)
    conversation_participants.each do |participant, is_sender|
      last_at = is_sender.eql?("true") ? "last_sent_at" : "last_received_at"
      participations.build(:person_id => participant,
                           :is_read => is_sender,
                           last_at.to_sym => DateTime.now)
    end
  end
  
  # Returns last received or sent message
  def last_message(user, received = true, count = -1)
    (messages[count].sender.eql?(user) == received) ? last_message(user, received, (count-1)) : messages[count]
  end
  
  def other_party(person)
    participants.reject { |p| p.id == person.id }.first
  end  

  def read_by?(person)
    participations.where(["person_id LIKE ?", person.id]).first.is_read
  end
  
  # If listing is an offer, return request, otherwise return offer
  def discussion_type
    listing.listing_type.eql?("request") ? "offer" : "request"
  end
  
  def can_be_cancelled?
    participations.each { |p| return false unless p.feedback_can_be_given? }
    return true
  end

  def has_feedback_from?(person)
    participations.find_by_person_id(person.id).has_feedback?
  end
  
  def feedback_skipped_by?(person)
    participations.find_by_person_id(person.id).feedback_skipped?
  end
  
  # Send email notification to message receivers and returns the receivers
  def send_email_to_participants(host)
    recipients(messages.last.sender).each do |recipient|
      if recipient.should_receive?("email_about_new_messages")
        PersonMailer.new_message_notification(messages.last, host).deliver
      end  
    end
  end
  
  # Returns all the participants except the message sender
  def recipients(sender)
    participants.reject { |p| p.id == sender.id }
  end
  
  def change_status(new_status, current_user, request)
    update_attribute(:status, new_status)
    participations.find_by_person_id(current_user.id).update_attribute(:is_read, true)
    if other_party(current_user).should_receive?("email_when_conversation_#{new_status}")
      PersonMailer.conversation_status_changed(self, request.host).deliver
    end      
  end
  
  def has_feedback_from_all_participants?
    participations.each { |p| return false if p.feedback_can_be_given? }
    return true
  end
  
  def offerer
    participants.each { |p| return p if listing.offerer?(p) }
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_filter :only => [ :new, :create ] do |controller|
    controller.ensure_logged_in "you_must_log_in_to_send_a_message"
  end
  
  before_filter :except => [ :new, :create ] do |controller|
    controller.ensure_logged_in "you_must_log_in_to_view_your_inbox"
  end
  
  before_filter :only => [ :index, :received, :sent, :notifications ] do |controller|
    controller.ensure_authorized "you_are_not_authorized_to_view_this_content"
  end
  
  before_filter :ensure_authorized_to_view_message, :only => [ :show, :accept, :reject ]
  before_filter :save_current_inbox_path, :only => [ :received, :sent, :show ]
  before_filter :ensure_listing_is_open, :only => [ :new, :create ]
  before_filter :ensure_listing_author_is_not_current_user, :only => [ :new, :create ]
  before_filter :ensure_authorized_to_reply, :only => [ :new, :create ]
  
  def index
    redirect_to received_person_messages_path(:person_id => @current_user.id)
  end
  
  def received
    params[:page] = 1 unless request.xhr?
    @conversations = @current_user.messages_that_are("received").paginate(:per_page => 15, :page => params[:page])
    request.xhr? ? (render :partial => "additional_messages") : (render :action => :index)
  end
  
  def sent
    params[:page] = 1 unless request.xhr?
    @conversations = @current_user.messages_that_are("sent").paginate(:per_page => 15, :page => params[:page])
    request.xhr? ? (render :partial => "additional_messages") : (render :action => :index)
  end
  
  def notifications
    @notifications = @current_user.notifications.paginate(:per_page => 20, :page => params[:page])
    @unread_notifications = @current_user.notifications.unread.all
    @current_user.mark_all_notifications_as_read
    logger.info "Unread: #{@unread_notifications.inspect}"
    render :partial => "additional_notifications" if request.xhr?
  end
  
  def show
    @current_user.read(@conversation) unless @conversation.read_by?(@current_user)
  end

  def new
    @conversation = Conversation.new
    @conversation.messages.build
    @conversation.participants.build
    render :action => :new, :layout => "application"
  end
  
  def create
    @conversation = Conversation.new(params[:conversation])
    if @conversation.save
      flash[:notice] = @conversation.listing ? "#{@conversation.listing.category}_#{@conversation.listing.listing_type}_message_sent" : "message_sent"
      Delayed::Job.enqueue(MessageSentJob.new(@conversation.id, @conversation.messages.last.id, request.host))
      redirect_to (session[:return_to_content] || root)
    else
      render :action => :new
    end  
  end
  
  def accept
    change_status("accepted")
  end
  
  def reject
    change_status("rejected")
  end
  
  private
  
  # Saves current path so that the user can be
  # redirected back to that path when needed.
  def save_current_inbox_path
    session[:return_to_inbox_content] = request.fullpath
  end
  
  def change_status(status)
    @conversation.change_status(status, @current_user, request)
    flash.now[:notice] = "#{@conversation.discussion_type}_#{status}"
    if status.eql?("accepted")
      Delayed::Job.enqueue(ConversationAcceptedJob.new(@conversation.id, request.host))
    end
    respond_to do |format|
      format.html { render :action => :show }
      format.js { render :layout => false }
    end
  end
  
  def ensure_authorized_to_view_message
    @conversation = Conversation.find(params[:id])
    unless @conversation.participants.include?(@current_user)
      flash[:error] = "you_are_not_authorized_to_view_this_content"
      redirect_to root and return
    end
  end
  
  def ensure_listing_is_open
    @listing = params[:conversation] ? Listing.find(params[:conversation][:listing_id]) : Listing.find(params[:id])
    if @listing.closed?
      flash[:error] = "you_cannot_reply_to_a_closed_#{@listing.listing_type}"
      redirect_to (session[:return_to_content] || root)
    end
  end
  
  def ensure_listing_author_is_not_current_user
    if current_user?(@listing.author)
      flash[:error] = "you_cannot_reply_to_your_own_#{@listing.listing_type}"
      redirect_to (session[:return_to_content] || root)
    end  
  end
  
  # Ensure that only users with appropriate visibility settings can reply to the listing
  def ensure_authorized_to_reply
    unless @listing.visible_to?(@current_user, @current_community)
      flash[:error] = "you_are_not_authorized_to_view_this_content"
      redirect_to root and return
    end  
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
  
  def get_message_title(listing)
    t(".#{listing.category}_#{listing.listing_type}_message_title", :title => @listing.title)
  end
  
  # Class is selected if conversation type is currently selected
  def get_inbox_tab_class(tab_name)
    current_tab_name = params[:conversation_type] || action_name || "received"
    current_tab_name = "received" if current_tab_name.eql?("show")
    "inbox_tab_#{current_tab_name.eql?(tab_name) ? 'selected' : 'unselected'}"
  end
  
end

app/views/conversations/_additional_messages.haml
= render :partial => "inbox_spacer" unless @conversations.empty?
= render :partial => "#{action_name}_conversation", :collection => @conversations, :as => :conversation, :spacer_template => "inbox_spacer"

app/views/conversations/_additional_notifications.haml
= render :partial => "inbox_spacer" unless @notifications.empty?
= render :partial => "notification", :collection => @notifications, :as => :notification, :spacer_template => "inbox_spacer"

app/views/conversations/_inbox_spacer.haml
.inbox_spacer

app/views/conversations/_message.haml
.message
  - if current_user?(message.sender)
    .message_content_spacer
      &nbsp;
  - else
    .person_image_message
      = small_avatar_thumb(message.sender)
    .message_arrow_left
      &nbsp;
  .message_main
    .message_sender
      = link_to message.sender.name, message.sender
      %span
        = l(message.created_at, :format => :short) + ":"
    .message_content_div
      - text_with_line_breaks do  
        = message.content
  - if current_user?(message.sender)
    .message_arrow_right
      &nbsp;
    .person_image_message
      = small_avatar_thumb(message.sender)  

app/views/conversations/_notification.haml
.notification{:class => (@unread_notifications.include?(notification) ? "unread" : "")}
  .notification_date
    = l(notification.created_at, :format => :short)
  .notification_content  
    = render :partial => "conversations/notifications/#{notification.type.downcase}", :locals => { :notification => notification }

app/views/conversations/_received_conversation.haml
- last_message = conversation.last_message(@current_user)
.conversation{:class => (conversation.read_by?(@current_user) ? "" : "unread"), :id => "conversation_#{conversation.id.to_s}"}
  .person_image
    = small_avatar_thumb conversation.other_party(@current_user)
  .conversation_left
    = link_to last_message.sender.name, last_message.sender
    %br/
    %span= l last_message.created_at, :format => :shorter
  .conversation_center
    %h3= link_to conversation.title, single_conversation_path(:conversation_type => action_name, :id => conversation.id)
    %span= link_to(truncate(last_message.content, :length => 60, :omission => "..."), single_conversation_path(:conversation_type => action_name, :id => conversation.id))
  .conversation_right
    %div{:id => "conversation_#{conversation.id.to_s}_status"}
      = render :partial => "status", :locals => { :conversation => conversation }

app/views/conversations/_status.haml
- if conversation.listing
  - if conversation.status.eql?("pending")
    - if current_user?(conversation.listing.author)
      - ["accept", "reject"].each do |status|
        = render :partial => "status_link", :locals => { :conversation => conversation, :status => status }
    - else
      .conversation_status_container
        .conversation_status_label
          = t(".waiting_confirmation_from_listing_author")
  - elsif conversation.status
    .conversation_status_container
      .conversation_status_label{:class => conversation.status}
        = t(".#{conversation.discussion_type}_#{conversation.status}")
      - if conversation.status.eql?("accepted")
        .conversation_status_label_links
          - if conversation.has_feedback_from?(@current_user)
            = t(".feedback_given")
          - elsif conversation.feedback_skipped_by?(@current_user)
            = t(".feedback_skipped")
          - else
            = link_to t(".give_feedback"), new_person_message_feedback_path(:person_id => @current_user.id, :message_id => conversation.id.to_s)
            &nbsp;|&nbsp;
            = link_to t(".skip_feedback"), skip_person_message_feedbacks_path(:person_id => @current_user.id, :message_id => conversation.id.to_s), :remote => true, :method => :put
  

      

app/views/conversations/_status_link.haml
.conversation_status_link{:class => status}
  - path = status.eql?("accept") ? accept_person_message_path(:person_id => @current_user.id, :id => conversation.id.to_s) : reject_person_message_path(:person_id => @current_user.id, :id => conversation.id.to_s)
  = link_to(image_tag("/images/icons/#{status}_icon.png") + t(".#{status}_#{conversation.discussion_type}"), path, :remote => true, :method => :put) 

app/views/conversations/accept.js.erb
/* Display notice */
$("#notification_container").html("<%= escape_javascript(render(:partial => 'layouts/notifications')) %>");

/* Update conversation status label */
$("#conversation_<%= @conversation.id.to_s %>_status").html("<%= escape_javascript(render(:partial => 'conversations/status', :locals => { :conversation => @conversation })) %>");

/* Remove unread color */
$("#conversation_<%= @conversation.id.to_s %>").removeClass("unread");

/* Update unread messages count */
$("#logged_in_messages_icon").html("<%= escape_javascript(render(:partial => 'layouts/logged_in_messages_icon')) %>");

app/views/conversations/index.haml
- if @conversations && !@conversations.empty?
  #conversations
    = render :partial => "conversations/#{action_name}_conversation", :collection => @conversations, :as => :conversation, :spacer_template => "inbox_spacer"
    = will_paginate(@conversations)
    = pageless(@conversations.total_pages, '#conversations', "#{action_name}", t('.loading_more_messages')) 
- else
  #no_conversations
    = t(".no_#{action_name}_messages")
  

app/views/conversations/new.haml
- content_for :javascript do
  - default_message_text = t(".default_#{@listing.listing_type}_message_text")
  initialize_send_message_form('#{default_message_text}','#{I18n.locale}');

.grid_10.prefix_7.suffix_7
  #new_message_form
    %h2
      = t(".#{@listing.category}_#{@listing.listing_type}_message_form_title")
      = link_to(@listing.author.given_name_or_username, @listing.author)
    = form_for @conversation, :url => person_messages_path(:person_id => @current_user.id) do |form|
      = form.error_messages
      .form_field_container
        .title_label
          = t(".title") + ":"
        .title_content
          = get_message_title(@listing)
          = form.hidden_field :title, :value => get_message_title(@listing)
      .form_field_container
        = fields_for "conversation[message_attributes]", Message.new do |message_form|
          = message_form.label :content, t('.message') + ":"
          = message_form.text_area :content, :class => "text_area"
          = message_form.hidden_field :sender_id, :value => @current_user.id
      .form_field_container
        = hidden_field_tag "conversation[conversation_participants][#{@current_user.id}]", true
        = hidden_field_tag "conversation[conversation_participants][#{@listing.author.id}]", false
        = form.hidden_field :listing_id, :value => @listing.id
        = form.submit t(".send_#{@listing.discussion_type}_message"), :class => "send_button"

app/views/conversations/notifications.haml
- if @notifications.empty?
  #no_conversations
    = t(".no_notifications")
- else
  #conversations
    = render :partial => "notification", :collection => @notifications, :as => :notification, :spacer_template => "inbox_spacer"
    = will_paginate(@notifications)
    = pageless(@notifications.total_pages, '#conversations', "#{action_name}", t('.loading_more_notifications'))
  

app/views/conversations/reject.js.erb
/* Display notice */
$("#notification_container").html("<%= escape_javascript(render(:partial => 'layouts/notifications')) %>");

/* Update conversation status label */
$("#conversation_<%= @conversation.id.to_s %>_status").html("<%= escape_javascript(render(:partial => 'conversations/status', :locals => { :conversation => @conversation })) %>");

/* Remove unread color */
$("#conversation_<%= @conversation.id.to_s %>").removeClass("unread");

/* Update unread messages count */
$("#logged_in_messages_icon").html("<%= escape_javascript(render(:partial => 'layouts/logged_in_messages_icon')) %>");

app/views/conversations/show.haml
- content_for :javascript do
  initialize_reply_form('#{I18n.locale}');

.grid_24
  .grid_11.alpha
    #conversation_title
      %h2= @conversation.title
      - if @conversation.listing
        - if current_user?(@conversation.messages.first.sender)
          = t(".#{@conversation.listing.listing_type}_sent_to")
          = link_to @conversation.other_party(@conversation.messages.first.sender).name, @conversation.other_party(@conversation.messages.first.sender)
        - else
          = t(".#{@conversation.listing.listing_type}_sent_by")
          = link_to @conversation.messages.first.sender.name, @conversation.messages.first.sender
        = t(".in_response_to_#{@conversation.listing.listing_type}")
        = link_to @conversation.listing.title, @conversation.listing
  .grid_13.omega
    #conversation_status
      %div{:id => "conversation_#{@conversation.id.to_s}_status"}
        = render :partial => "status", :locals => { :conversation => @conversation }
  
.grid_24
  #messages
    = render :partial => "message", :collection => @conversation.messages
  
  #conversation_notice
    
  #reply_form
    = form_for Message.new, :url => person_message_messages_path(:person_id => @current_user.id, :message_id => @conversation.id.to_s), :remote => true do |f|
      .message_form_field_container
        = f.label :content, t(".write_a_reply")
      .message_form_field_container  
        = f.text_area :content
      .message_form_field_container
        = f.hidden_field :conversation_id, :value => @conversation.id.to_s
        = f.hidden_field :sender_id, :value => @current_user.id
        = f.submit t(".send_reply"), :class => "send_button"