config/routes.rb
require 'subdomain'

Kassi::Application.routes.draw do

  
  scope "(/:locale)" do
    devise_for :people, :controllers => { :confirmations => "confirmations" }
    
    namespace :admin do
      resources :feedbacks
    end
    resources :listings do
      collection do
        get :more_listings
        get :browse
        get :random
      end
      resources :images, :controller => :listing_images
      resources :comments
    end
    resources :people do
      collection do
        get :check_username_availability
        get :check_email_availability
        get :check_invitation_code
        get :not_member
      end
      member do 
        put :update_avatar
        put :activate
        put :deactivate
      end
      resources :listings do
        member do 
          put :close
        end  
      end  
      resources :messages, :controller => :conversations do 
        collection do
          get :received
          get :sent
          get :notifications
        end
        member do
          put :accept
          put :reject
          put :cancel
        end
        resources :messages
        resources :feedbacks, :controller => :testimonials do
          collection do
            put :skip
          end  
        end    
      end
      resource :settings do
        member do
          get :profile
          get :avatar
          get :account
          get :notifications
        end
      end
      resources :badges
      resources :testimonials
    end
    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :register_details
      end  
    end
    resource :terms do
      member do
        post :accept
      end  
    end    
    resources :sessions do
      collection do
        post :request_new_password
      end
    end  
    resources :consent
    resource :sms do
      get :message_arrived
    end
    resources :contact_requests do
      collection do
        get :thank_you
      end
    end
  end
  
  match '/badges/:style/:id.:format' => "badges#image"
  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/:locale/load" => "listings#load", :as => :load
  match "/:locale/loadmap" => "listings#loadmap", :as => :loadmap
  match "/:locale/offers" => "listings#offers", :as => :offers
  match "/:locale/requests" => "listings#requests", :as => :requests
  match "/:locale/offers/tag/:tag" => "listings#offers", :as => :offers_with_tag
  match "/:locale/requests/tag/:tag" => "listings#requests", :as => :requests_with_tag
  match "/:locale/people/:id/:type" => "people#show", :as => :person_listings
  match "/:locale/people/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation
  match "/:locale/people/:person_id/messages" => "conversations#received", :as => :reply_to_listing
  match "/:locale/listings/:id/reply" => "conversations#new", :as => :reply_to_listing
  match "/:locale/listings/new/:type/:category" => "listings#new", :as => :new_request_category
  match "/:locale/listings/new/:type" => "listings#new", :as => :new_request
  match "/:locale/search" => "search#show", :as => :search
  match "/:locale/logout" => "sessions#destroy", :as => :logout, :method => :delete
  match "/:locale/signup" => "people#new", :as => :sign_up
  match "/:locale/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
  match "/:locale/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
  match "/:locale/login" => "sessions#new", :as => :login
  match "/change_locale" => "i18n#change_locale"
  match '/:locale/tag_cloud' => "tag_cloud#index", :as => :tag_cloud
  match "/:locale/offers/map/" => "listings#offers_on_map", :as => :offers_on_map
  match "/:locale/requests/map/" => "listings#requests_on_map", :as => :requests_on_map
  match "/api/query" => "listings#serve_listing_data", :as => :listings_data
  match "/:locale/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
  match "/:locale/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
  
  constraints(Subdomain) do
    match '/:locale/' => 'homepage#index'
    match '/' => 'homepage#index'
  end  
  
  match '/:locale' => 'dashboard#index'
  
  root :to => 'dashboard#index'
  
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base

  GRADES = [
    [ "less_than_expected", { :form_value => "1", :db_value => 0, :default => false } ],
    [ "slightly_less_than_expected", { :form_value => "2", :db_value => 0.25, :default => false } ],
    [ "as_expected", { :form_value => "3", :db_value => 0.5, :default => false } ],
    [ "slightly_better_than_expected", { :form_value => "4", :db_value => 0.75, :default => false } ],
    [ "exceeded_expectations", { :form_value => "5", :db_value => 1, :default => false } ]
  ]

  belongs_to :author, :class_name => "Person", :dependent => :destroy
  belongs_to :receiver, :class_name => "Person", :dependent => :destroy
  belongs_to :participation, :dependent => :destroy

  validates_inclusion_of :grade, :in => 0..1, :allow_nil => false
  
  scope :positive, where("grade >= 0.5")

  # Formats grade so that it can be displayed in the UI
  def displayed_grade
    (grade * 4 + 1).to_i
  end
  
  def notify_receiver(host)
    TestimonialNotification.create(:testimonial_id => id, :receiver_id => receiver.id)
    if receiver.should_receive?("email_about_new_received_testimonials")
      PersonMailer.new_testimonial(self, host).deliver
    end
  end

end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  
  before_filter :except => :index do |controller|
    controller.ensure_logged_in "you_must_log_in_to_give_feedback"
  end
  
  before_filter :ensure_authorized_to_give_feedback, :except => :index
  before_filter :ensure_feedback_not_given, :except => :index
  before_filter :person_belongs_to_current_community, :only => :index
  
  def index
    @testimonials = @person.received_testimonials.paginate(:per_page => 10, :page => params[:page])
    @grade_amounts = @person.grade_amounts
    render :partial => "additional_testimonials" if request.xhr?
  end
  
  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = Testimonial.new(params[:testimonial])
    if @testimonial.save
      Delayed::Job.enqueue(TestimonialGivenJob.new(@testimonial.id, request.host))
      flash[:notice] = ["feedback_sent_to", @conversation.other_party(@current_user).given_name_or_username, @conversation.other_party(@current_user)]
      redirect_to (session[:return_to_inbox_content] || person_message_path(:person_id => @current_user.id, :id => @conversation.id))
    else
      render :action => new
    end    
  end
  
  def skip
    @participation.update_attribute(:feedback_skipped, true)
    flash[:notice] = "feedback_skipped"
    respond_to do |format|
      format.html { redirect_to single_conversation_path(:conversation_type => "received", :person_id => @current_user.id, :id => @conversation.id) }
      format.js { render :layout => false }
    end
  end
  
  private
  
  def ensure_authorized_to_give_feedback
    @conversation = Conversation.find(params[:message_id])
    @participation = Participation.find_by_person_id_and_conversation_id(@current_user, @conversation)
    unless @participation
      flash[:error] = "you_are_not_allowed_to_give_feedback_on_this_transaction"
      redirect_to root and return
    end
  end
  
  def ensure_feedback_not_given
    unless @participation.feedback_can_be_given? 
      flash[:error] = "you_have_already_given_feedback_about_this_event"
      redirect_to root and return
    end  
  end

end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
  
  
  
end

app/views/testimonials/_additional_testimonials.haml
= render :partial => "conversations/inbox_spacer" unless @testimonials.empty?
= render :partial => @testimonials, :spacer_template => "conversations/inbox_spacer"

app/views/testimonials/_feedback_type_description.haml
.feedback_type_description
  .feedback_type_description_image
    %div{:class => "profile_feedback_average_image_#{grade_amount[2]}_small"}
      &nbsp;  
  .feedback_type_description_text
    = t("people.profile_feedback.#{grade_amount[0]}")
  .feedback_type_description_grade{:id => "feedback_grade_#{grade_amount[2]}"}
    = grade_amount[1]

app/views/testimonials/_testimonial.haml
.single_testimonial{:class => "light_#{testimonial.displayed_grade > 2 ? 'green' : 'red' }"}
  - listing = testimonial.participation.conversation.listing
  .testimonial_image
    %div{:class => grade_image_class(testimonial.displayed_grade, false), :title => t("people.profile_feedback.grade").capitalize + " " + grade_text(testimonial.displayed_grade).downcase + "."}
      &nbsp;
  .testimonial_description
    = link_to testimonial.author.given_name_or_username, testimonial.author
    = t("people.profile_feedback.#{profile_testimonial_other_person_role(@person, listing)}ed_#{listing.category}")
    - if listing.visibility.eql?("disabled")
      &ldquo;#{listing.title}&rdquo;
    - else
      = link_to listing.title, listing
    = t(".#{profile_testimonial_other_person_role(@person, listing).eql?('request') ? 'from' : 'to'}_user")
    = @person.given_name_or_username
    = time_ago(testimonial.created_at) + "."
    - unless !testimonial.text || testimonial.text.eql?("")
      %br/
      .testimonial_description_text
        - text_with_line_breaks do
          &ldquo;#{testimonial.text}&rdquo;
      

app/views/testimonials/index.haml
- content_for :javascript do
  initialize_profile_feedback_view();

= render :partial => "layouts/profile_extras_header"

- if @testimonials && !@testimonials.empty?
  #testimonials_grade_image.grid_4
    %div{:class => "#{grade_image_class(@person.feedback_average)}_big"}
      &nbsp;
  #feedback_average.grid_10
    .feedback_average_title
      = t("people.show.feedback_average")
    .feedback_average_value
      = @person.feedback_average.to_s + "/5"
    .feedback_average_description
      = "(" + grade_text(@person.feedback_average) + ")"
    .feedback_average_description_link_div
      = link_to t("common.what_is_this"), "#", :id => "help_feedback_link"
  .grid_10
    #feedback_type_descriptions
      = render :partial => "common/staples", :locals => { :temp_class => "staples_top" }
      %h4= t(".feedback_altogether") + @testimonials.total_entries.to_s
      #feedback_type_description_list
        = render :partial => "feedback_type_description", :collection => @grade_amounts, :as => :grade_amount
      = render :partial => "common/staples", :locals => { :temp_class => "staples_bottom" }
  .clear
  #all_testimonials
    %h2= t(".all_testimonials") + " (#{@testimonials.total_entries})"
    = render :partial => @testimonials, :spacer_template => "conversations/inbox_spacer"
    = will_paginate(@testimonials)
    = pageless(@testimonials.total_pages, '#all_testimonials', person_testimonials_path(@person), t('.loading_more_testimonials')) 
- else
  #no_conversations
    = t(".no_testimonials")
    
= render :partial => "people/help_texts", :locals => { :field => "feedback_description" }

app/views/testimonials/new.haml
- content_for :javascript do
  initialize_give_feedback_form('#{I18n.locale}','#{t('error_messages.testimonials.you_must_select_a_grade')}','#{t('error_messages.testimonials.you_must_explain_not_neutral_feedback')}');

.grid_10.prefix_7.suffix_7
  #new_testimonial_form
    %h2
      = t(".give_feedback_to", :person => @conversation.other_party(@current_user).given_name_or_username)
    = form_for @testimonial, :url => person_message_feedbacks_path(:person_id => @current_user.id, :message_id => @conversation.id) do |form|
      = form.error_messages
      .message_form_field_container
        = form.label :grade, t(".grade") + ":", :class => "normal"
        %br/
        .feedback_grade_images
          - Testimonial::GRADES.each do |grade| 
            %label{:for => "grade-#{grade[1][:form_value]}", :class => "radio"}
              = radio_button_tag "testimonial[grade]", grade[1][:db_value], grade[1][:default], :id => "grade-#{grade[1][:form_value]}" 
              = t(".#{grade[0]}")
      .message_form_field_container
        = form.label :text, t('.textual_feedback') + ":", :class => "normal" 
        = form.text_area :text, :class => "text_area"
      .message_form_field_container
        = form.hidden_field :author_id, :value => @current_user.id
        = form.hidden_field :receiver_id, :value => @conversation.other_party(@current_user).id
        = form.hidden_field :participation_id, :value => @participation.id
        = form.submit t(".send_feedback"), :class => "send_button", :id => "send_testimonial_button"

app/views/testimonials/skip.js.erb
/* Display notice */
$("#notification_container").html("<%= escape_javascript(render(:partial => 'layouts/notifications')) %>");

/* Update conversation status label */
$("#conversation_<%= @conversation.id.to_s %>_status").html("<%= escape_javascript(render(:partial => 'conversations/status', :locals => { :conversation => @conversation })) %>");