config/routes.rb
require 'subdomain'

Kassi::Application.routes.draw do

  
  scope "(/:locale)" do
    devise_for :people, :controllers => { :confirmations => "confirmations" }
    
    namespace :admin do
      resources :feedbacks
    end
    resources :listings do
      collection do
        get :more_listings
        get :browse
        get :random
      end
      resources :images, :controller => :listing_images
      resources :comments
    end
    resources :people do
      collection do
        get :check_username_availability
        get :check_email_availability
        get :check_invitation_code
        get :not_member
      end
      member do 
        put :update_avatar
        put :activate
        put :deactivate
      end
      resources :listings do
        member do 
          put :close
        end  
      end  
      resources :messages, :controller => :conversations do 
        collection do
          get :received
          get :sent
          get :notifications
        end
        member do
          put :accept
          put :reject
          put :cancel
        end
        resources :messages
        resources :feedbacks, :controller => :testimonials do
          collection do
            put :skip
          end  
        end    
      end
      resource :settings do
        member do
          get :profile
          get :avatar
          get :account
          get :notifications
        end
      end
      resources :badges
      resources :testimonials
    end
    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :register_details
      end  
    end
    resource :terms do
      member do
        post :accept
      end  
    end    
    resources :sessions do
      collection do
        post :request_new_password
      end
    end  
    resources :consent
    resource :sms do
      get :message_arrived
    end
    resources :contact_requests do
      collection do
        get :thank_you
      end
    end
  end
  
  match '/badges/:style/:id.:format' => "badges#image"
  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/:locale/load" => "listings#load", :as => :load
  match "/:locale/loadmap" => "listings#loadmap", :as => :loadmap
  match "/:locale/offers" => "listings#offers", :as => :offers
  match "/:locale/requests" => "listings#requests", :as => :requests
  match "/:locale/offers/tag/:tag" => "listings#offers", :as => :offers_with_tag
  match "/:locale/requests/tag/:tag" => "listings#requests", :as => :requests_with_tag
  match "/:locale/people/:id/:type" => "people#show", :as => :person_listings
  match "/:locale/people/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation
  match "/:locale/people/:person_id/messages" => "conversations#received", :as => :reply_to_listing
  match "/:locale/listings/:id/reply" => "conversations#new", :as => :reply_to_listing
  match "/:locale/listings/new/:type/:category" => "listings#new", :as => :new_request_category
  match "/:locale/listings/new/:type" => "listings#new", :as => :new_request
  match "/:locale/search" => "search#show", :as => :search
  match "/:locale/logout" => "sessions#destroy", :as => :logout, :method => :delete
  match "/:locale/signup" => "people#new", :as => :sign_up
  match "/:locale/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
  match "/:locale/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
  match "/:locale/login" => "sessions#new", :as => :login
  match "/change_locale" => "i18n#change_locale"
  match '/:locale/tag_cloud' => "tag_cloud#index", :as => :tag_cloud
  match "/:locale/offers/map/" => "listings#offers_on_map", :as => :offers_on_map
  match "/:locale/requests/map/" => "listings#requests_on_map", :as => :requests_on_map
  match "/api/query" => "listings#serve_listing_data", :as => :listings_data
  match "/:locale/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
  match "/:locale/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
  
  constraints(Subdomain) do
    match '/:locale/' => 'homepage#index'
    match '/' => 'homepage#index'
  end  
  
  match '/:locale' => 'dashboard#index'
  
  root :to => 'dashboard#index'
  
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  
  skip_filter :check_email_confirmation
  
  def about
  end
  
  def how_to_use
  end

  def terms
  end
  
  def register_details
  end

end

app/helpers/infos_helper.rb
module InfosHelper
  
  # Class is selected if conversation type is currently selected
  def get_infos_tab_class(tab_name)
    current_tab_name = action_name || "about"
    "inbox_tab_#{current_tab_name.eql?(tab_name) ? 'selected' : 'unselected'}"
  end
  
end

app/views/infos/how_to_use.en.haml
%h3 Offer items and favors to others

%p
  Do you own tools, phones, housing, I.T Equipment, sports equipment, funny costumes or other items that you do not use often and could easily lend to others, or even sell or give them away? Are you good at fixing bikes, sewing or perhaps eager to walk dogs? Would you be willing to give a ride to somebody for some gas money when travelling to work? Do you have an apartment waiting for someone to rent it? 
  = link_to "Add information about all these to Kassi", new_request_path(:type => "offer")
  and experience the joy of helping your fellow man!

%p
  Also remember to 
  = link_to("check what other people need at the moment", requests_path) + "."
  Maybe you can offer something that someone is currently requesting.

%p
  Kassi aims to bring together people who need something and who can offer something. They can then freely discuss on the methods of exchange. This means that you sell, rent and trade or give, lend and help others for free.

%h3 Ask others what you need

%p
  Whether you need an item, a favor, a ride or an apartment, they can all be found using Kassi's useful
  = link_to("search", search_path) + "."
  You can also
  = link_to("browse open offers", offers_path) + "."

%p
  If somebody is already offering what you need in Kassi, you can click the "request" or "reply" link in that offer and send a free message to the person who created the offer using the form that opens up. After that you only need to wait for the recipient of the message to accept your request. You can agree on the details of the exchange by Kassi's messaging functionality. You will get an automatic email notification from all new messages and accepted requests and offers. Thus, there's no need for you to reveal your email address to the other party unless you wish to do so. You can view all your received and sent messages and accepted, rejected and pending requests and offers in the
  - if logged_in?
    = link_to("messages view", person_messages_path(:person_id => @current_user.id)) + ","
  - else 
    messages view,
  which you can always access by clicking the envelope icon on the top of each page, when you have logged in to Kassi.

%p
  If you did not find what you are looking for, you can
  = link_to("create an open request", new_request_path(:type => "request")) + ","
  where you describe what you need. This request will be shown to all other Kassi users. It is very likely that somebody can offer just the thing you need.
  
%h3 Tips

%p
  The more trustworthy you appear to other people, the more eager they probably are to offer you the things you need. The easiest way to build your credibility is to
  - if logged_in?
    = link_to("fill out your profile information carefully", profile_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    fill out your profile information carefully.
  You should at least fill in your full name and
  - if logged_in?
    = link_to("add a recognizable profile picture of yourself", avatar_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    add a recognizable profile picture of yourself.

%p
  When you offer something to other users or they offer something to you, it's always good to give feedback to the other party after the transaction. Good feedback will make people happy, and if somebody doesn't go the way you think you should, it's also good to leave a note about that. All feedback is public and is shown in the profile of the person who received the feedback, and thus helps the other people to assess the credibility of that person. For that reason you should also remind others to give feedback to you, because the positive feedback builds your credibility in the eyes of others, and smoothens future transactions. You can give feedback by clicking the "Give Feedback" link on an accepted request or offer in the messages view.
  
-if APP_CONFIG.use_sms
  %p
    Before posting offers or requests with sms you have to have added your mobile phone number in international format
    - if logged_in?
      = link_to("in your profile.", profile_person_settings_path(:person_id => @current_user.id)) + "." 
    - else
      in your profile.

  %p 
    Sms features are still a work in progress, so there might be small glitches here and there. Please send  
    = link_to "feedback", "#", :id => "give_feedback_link"
    if you notices any problems or have ideas about how to improve the feature.

app/views/infos/how_to_use.fi.haml
%h3 Lisää tavarasi ja taitosi tarjolle

%p
  Omistatko työkaluja, urheiluvälineitä, naamiaisasuja tai muita vastaavaa tavaroita, joita et käytä usein ja voisit hyvin lainata muille, tai kenties myydä tai antaa kokonaan pois? Oletko taitava pyöränkorjaaja, näppärä ompelija tai kenties ulkoilutat mielelläsi koiria? Liikutko usein autolla ja ottaisit mielelläsi ihmisiä kyytiin bensarahoja vastaan? Onko sinulla asunto vailla vuokralaista?
  = link_to "Lisää Kassiin tieto kaikista näistä", new_request_path(:type => "offer")
  ja koe auttamisen ilo!

%p
  Kannattaa myös tarkistaa, 
  = link_to("mitä ihmiset tällä hetkellä kaipaavat", requests_path) + "."
  Kukaties pystyt tarjoamaan juuri jotain sellaista, mitä joku toinen on pyytänyt.
  
%p
  Kassin tarkoitus on yhdistää tarvitsijat ja tarjoajat, ja he voivat sopia keskenään vapaasti mahdollisista vastineista. Palvelussa voi siis myydä, vuokrata ja vaihtaa tai antaa, lainata ja auttaa ihan ilmaiseksi pelkkää hyvää mieltä vastaan.
  
%h3 Pyydä muilta tarvitsemaasi

%p
  Tarvitsitpa sitten tavaraa, palvelusta, kyytiä tai asuntoa, kaikki löytyvät helpoiten Kassin kätevällä
  = link_to("hakutoiminnolla", search_path) + "."
  Vaihtoehtoisesti voit
  = link_to("selata avoimia tarjouksia", offers_path) + "."

%p
  Jos joku tarjoaa jo Kassissa sitä mitä tarvitset, voit klikata kyseisen tarjouksen "pyydä"-linkkiä ja lähettää kyseiselle käyttäjälle vapaamuotoisen viestin. Sen jälkeen sinun tarvitsee enää odottaa, että viestin vastaanottaja hyväksyy pyyntösi. Viestien välityksellä voitte sopia tarkemmin tapahtuman yksityiskohdista. Saat uusista viesteistä ja pyynnön hyväksynnästä automaattisesti tiedon sähköpostiisi, joten sinun ei tarvitse paljastaa toiselle osapuolelle sähköpostiosoitettasi, ellet niin halua. Näet saapuneet ja lähetetyt viestisi sekä hyväksytyt ja hyväksymättömät pyyntösi ja tarjouksesi
  - if logged_in?
    = link_to("viestinäkymässä", person_messages_path(:person_id => @current_user.id)) + ","
  - else 
    viestinäkymässä,
  johon pääset aina kätevästi yläreunassa olevan kirjekuori-ikonin kautta, kun olet kirjautunut sisään Kassiin.

%p
  Jos et löytänyt Kassista tarvitsemaasi, voit 
  = link_to("luoda avoimen pyynnön", new_request_path(:type => "request")) + ","
  jossa kerrot mitä tarvitset. Pyyntö näytetään kaikille Kassin käyttäjille. Todennäköisesti joku toinen Kassin käyttäjistä pystyy tarjoaaman juuri tarvitsemasi asian.
  
%h3 Vinkkejä

%p
  Mitä luotettavammalta vaikutat muiden Kassin käyttäjien silmissä, sitä innokkaampia he ovat tarjoamaan sinulle pyytämiäsi asioita. Helppo tapa lisätä luotettavuutta on 
  - if logged_in?
    = link_to("täyttää omat profiilitiedot huolellisesti", profile_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    täyttää omat profiilitiedot huolellisesti. 
  Erityisesti kannattaa muistaa esiintyä omalla nimellään ja 
  - if logged_in?
    = link_to("lisätä itselleen tunnistettava profiilikuva", avatar_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    lisätä itselleen tunnistettava profiilikuva.
  

%p
  Kun tarjoat jotain muille käyttäjille tai pyydät heiltä jotain, kannattaa aina muistaa antaa tapahtuman jälkeen palautetta toiselle osapuolelle. Hyvä palaute tuo toiselle osapuolelle hyvän mielen, ja jos toinen ei ole toiminut odotetulla tavalla, on myös siitä hyvä huomauttaa tälle. Palaute on julkista ja näkyy kaikille palautteen saaneen käyttäjän profiilissa, joten se auttaa muita käyttäjiä arvioimaan kyseisen käyttäjän luotettavuutta. Kannattaa siis myös kehottaa toisia käyttäjiä antamaan palautetta sinulle, sillä saamasi positiivisen palautteen myötä muut tietävät, että sinuun kannnattaa luottaa. Palautteen lisääminen tapahtuu viestinäkymässä klikkaamalla "Anna palautetta" -linkkiä hyväksytyn pyynnön tai tarjouksen kohdalla.
  
-if APP_CONFIG.use_sms
  %h3 Kimppakyytejä tekstiviestillä
  
  %p Kimppakyytitarjouksia ja -pyyntöjä voit jättää myös normaalihintaisella tekstiviestillä. Tämä voi olla kätevä tapa tarkistaa tarjolla olevat kyydit liikkeessä ollessa, tai ilmoittaa omista ajoaikeistaan vaikkapa autolle kävellessä. Kunhan olet lisännyt puhelinnumerosi kansainvälisessä muodossa (esim. +358501234567) profiiliisi, saat kyydin pyytäjänä heti tekstiviestillä tiedon, jos sopiva kyyti löytyy jo Kassista, tai kun sopiva tarjous lisätään.

  %p 
    Puhelinnumeron tulee olla lisättynä 
    - if logged_in?
      = link_to("profiiliin", profile_person_settings_path(:person_id => @current_user.id)) + "." 
    - else
      profiiliin
    ennen kuin tekstiviesti-ilmoituksia voi jättää, jotta ilmoitukset osataan merkitä oikealle henkilölle.
  
  %p Viesti tulee lähettää numeroon +358400312821 ja sen muoto on: "kassi kyyti pyyntö/tarjous lähtöpaikka määränpää kellonaika (vapaaehtoinen kuvausteksti)". Eli esimerkiksi:
  %ul
    %li kassi kyyti tarjous otakaari20 keskusta 18:30 vielä kaksi mahtuu kyytiin
    %li kassi kyyti pyyntö rautatieasema,hämeenlinna tampere 14:00
  
  %p Kassi yrittää päätellä osoitetiedoista yhteensopivia tarjouksia ja pyyntöjä, mutta erottelee tällä hetkellä viestin osat aina välilöynnillä, joten osoitenumerot tai tarkentavat kaupungit tulee kirjoittaa yhteen tai erottaa pilkulla (eikä välilyönnillä).
  
  %p Kellonajan oletetaan viittaavan aina seuraavan 24 tunnin sisällä olevaan aikaan, mutta jos haluat tehdä pyynnön tai tarjouksen pidemmälle tulevaisuuteen, voit merkitä ajaksi esim. 24.11.2010-17:30.
  
  %p 
    Tekstiviestitoiminnallisuus on vielä kokeiluasteella, joten pieniä virheitä saattaa esiintyä. Lähetä ihmeessä 
    = link_to "palautetta", "#", :id => "give_feedback_link"
    , jos huomaat kummallisuuksia tai sinulla on ajatuksia toiminnan kehittämiseksi.

app/views/infos/how_to_use.nl.haml
%h3 Biedt items en gunsten aan

%p
  Heb je gereedschap, sport spullen, gekke outfits of andere items die je niet vaak gebruikt en aan anderen kan uitlenen, verkopen of weggeven? Ben je goed in het maken van fietsen, naaien of laat je graag een hond uit? Ben jij bereid om iemand een lift naar het werk te geven in ruil voor brandstof? Heb jij een appartement die je kan verhuren? 
  = link_to "Voeg informatie over dit allemaal toe aan Kassi", new_request_path(:type => "Aanbod")
  en ervaar het geluk van het helpen van je medemens!

%p
  Vergeet ook niet om 
  = link_to("te kijken wat anderen op dit moment nodig hebben", requests_path) + "."
  Misschien heb jij iets te bieden wat iemand anders nodig heeft.

%p
  Kassi probeert mensen, die iets nodig hebben of iets aan te bieden hebben, samen te brengen. Zij kunnen vrij discuseren over de manier van uitwisselen. Dit betekend dat je gratis anderen verkoopt, verhuurd en ruilt of geeft, leent en anderen helpt. 

%h3 Vraag anderen wat je nodig hebt

%p
  Of je een item, gunst, rit of een appartement nodig hebt, het is allemaal te vinden door gebruik te maken van de zoekfunctie
  = link_to("search", search_path) + "."
  Je kan ook
  = link_to("browse open offers", offers_path) + "."

%p
  Als iemand al iets aanbiedt wat jij nodig hebt, kan je op de "verzoek" of "beantwoord" link in het aanbod klikken en een bericht naar de persoon, die het aabod gemaakt heeft, sturen. Daarna hoef je alleen maar te wachten tot de andere jou verzoek accepteert. Over de manier van uitwisselen kan je uitkomen door gebruik te maken van Kassi's messaging functionaliteit. Je ontvangt een automatische email notificatie van alle nieuwe berichten en geaccepteerde verzoeken en aanbiedingen. Dus het is niet nodig om je email adres bekend te maken aan de andere partij, tenzij jij dat wilt. Je kan al jou ontvangen en verzonden berichten zien in de
  - if logged_in?
    = link_to("inbox", person_messages_path(:person_id => @current_user.id)) + ","
  - else 
    inbox,
  welke je altijd kan openen door op het envelop icoontje boven aan elke pagina, te klikken.

%p
  Als je niet hIf you did not find what you are looking for, you can
  = link_to("create an open request", new_request_path(:type => "request")) + ","
  where you describe what you need. This request will be shown to all other Kassi users. It is very likely that somebody can offer just the thing you need.
  
%h3 Tips

%p
  The more trustworthy you appear to other people, the more eager they probably are to offer you the things you need. The easiest way to build your credibility is to
  - if logged_in?
    = link_to("fill out your profile information carefully", profile_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    fill out your profile information carefully.
  You should at least fill in your full name and
  - if logged_in?
    = link_to("add a recognizable profile picture of yourself", avatar_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    add a recognizable profile picture of yourself.

%p
  When you offer something to other users or they offer something to you, it's always good to give feedback to the other party after the transaction. Good feedback will make people happy, and if somebody doesn't go the way you think you should, it's also good to leave a note about that. All feedback is public and is shown in the profile of the person who received the feedback, and thus helps the other people to assess the credibility of that person. For that reason you should also remind others to give feedback to you, because the positive feedback builds your credibility in the eyes of others, and smoothens future transactions. You can give feedback by clicking the "Give Feedback" link on an accepted request or offer in the messages view.
  
-if APP_CONFIG.use_sms
  %h3 Ridesharing with SMS
  
  %p Ridesharing offers and requests can be added also with sms. It can be a handy way to check available rides on the move or announce your driving plans when walking towards your car. Kassi will inform the offer author by sms if the number is in the profile in the international form (e.g. +358501234567), when matching offers are found in Kassi.

  %p
    Before posting offers or requests with sms you have to have added your mobile phone number
    - if logged_in?
      = link_to("in your profile.", profile_person_settings_path(:person_id => @current_user.id)) + "." 
    - else
      in your profile.
  
  %p Messages should be sent to +358400312821 and be formed as: "kassi ride offer/request origin destination time (optional description)". For example:
  %ul
    %li kassi ride offer somestreet20 Helsinki 18:30 still place for two in the car
    %li kassi ride request railwaystation,hämeenlinna Tampere 14:00
  
  %p Currently Kassi separates all parts by spaces, so write addres numbers or other clarifications without space, to correct results. Kassi will search for matching request and offers based on the locations given.
  
  %p The time is expected to be within next 24 hours, but it is possible to write exact date if you want, e.g. 24.11.2010-17:30.
  
  %p 
    Sms features are still a work in progress, so there might be small glitches here and there. Please send  
    = link_to "feedback", "#", :id => "give_feedback_link"
    if you notices any problems or have ideas about how to improve the feature.

app/views/infos/how_to_use.ru.haml
%h3 Предложения товаров и услуг

%p
  У вас есть инструменты, спортивный инвентарь, смешные костюмы или другие вещи, которыми вы не пользуетесь, или пользуетесь очень редко и можете одолжить другим, или даже продать или просто отдать? Вы умеете ремонтировать велосипеды, шить или вам нравится выгуливать собак? Хотите кого-нибудь подвезти утром, по пути на работу? Или может быть у вас есть комната, которую вы можете сдать кому-либо? 
  = link_to "Разместите информацию об этом на Kassi", new_request_path(:type => "offer")
  и получите удовольствие помогая другим людям!

%p
  Кроме того, обратите внимание на 
  = link_to("то, что требуется сейчас другим", requests_path) + "."
  Может быть, у вас есть именно то, что они ищут.

%p
  Целью Kassi является помощь во встрече людям, которые ищут что-нибудь и тем, у которых есть что предложить другим. Они могут свободно договориться о способах обмена. Это означает, что вы можете продавать, покупать, сдавать, отдавать, и помогать другим людям. Бесплатно.

%h3 Узнайте, что необходимо другим

%p
  Нужна ли вам какая-либо вещь, услуга, поездка или жилище, всё это может быть легко найдено с помощью полезной функции
  = link_to("поиска", search_path) + "."
  Также вы можете
  = link_to("просмотреть открытые предложения", offers_path) + "."

%p
  Если кто-то уже предлагает то, что требуется вам, вы можете нажать ссылку «Запросить» или «Комментарий» в этом предложении и отправить сообщение пользователю, который создал это предложение, используя  форму. После этого вам останется только подождать, пока получатель сообщения ответит на него, либо примет ваш запрос. О деталях сделки можно договориться используя функции обмена сообщениями Kassi. Вы будете получать автоматические оповещения обо всех новых сообщениях, адресованных вам, а также о принятых предложениях или запросах. Таким образом не требуется раскрывать ваш адрес электронной почты кому-либо, за исключением случаев, когда вы сами этого хотите. Все полученные и отправленные сообщения, отвергнутые или находящиеся в процессе подтверждения предложения и запросы можно просмотреть в
  - if logged_in?
    = link_to("разделе «Cообщения»", person_messages_path(:person_id => @current_user.id)) + ","
  - else 
    разделе «Сообщения»,
  куда вы можете быстро перейти нажав значок с конвертом, расопложенный вверху каждой страницы, после того, как вы авторизуетесь.

%p
  Если вы не нашли то, что искали, вы можете
  = link_to("создать запрос", new_request_path(:type => "request")) + ","
  где можете описать всё, что вам необходимо. Этот запрос будет доступен всем другим пользователям Kassi. Очень может быть, что кто-нибудь сможет предложить именно то, что нужно вам.
  
%h3 Советы

%p
  Чем больше люди будут вам доверять, тем больше вероятность того, что кто-нибудь поможет вам отыскать необходимую вещь. Самый простой способ повысить уровень доверия к себе, это
  - if logged_in?
    = link_to("как можно более полное представление информации о себе", profile_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    как можно более полное представление информации о себе.
  По крайней мере вы должны указать своё имя и
  - if logged_in?
    = link_to("добавить разборчивое фото или картинку для учётной записи", avatar_person_settings_path(:person_id => @current_user.id)) + "." 
  - else
    добавить разборчивое фото или картинку для учётной записи.

%p
  Когда вы предлагаете что-нибудь другим пользователям, либо, если они предлагают что-либо вам, всегда приветствуется оставлять отзыв о каждой сделке. Хорошие отзывы сделают людей счастливее, а если кто-то поступил не так, как вы ожидали, об этом тоже следует рассказать. Все отзывы являются общедоступными и отображаются в профиле учётной записи пользователя, таким образом помогая другим пользователям составить представление об этом человеке. По этой же причине вам следует напоминать другим оставлять отзывы о вас, поскольку положительные отзывы будут влиять на уровень доверия к вам со стороны других пользователей и упростят дальнейшие сделки. Оставить отзыв можно нажав ссылку «Оставить отзыв» на странице принятого запроса или предложения в списке сообщений.
  
-if APP_CONFIG.use_sms
  %h3 Осуществляйте поездки с помощью SMS
  
  %p Предложения и запросы на своместное использование транспортных средств могут быть кроме того добавлены с помощью SMS. Это может быть удобным способом проверить список доступных поездок, либо поделиться с другими вашими планами, в то время, когда вы едете на своей машине. Kassi проинформирует автора предложения по sms, если телефон, указанный в его профиле имеет международный формат(н-р +7xxxxxxxxxx), если Kassi обнаружит совпадающие заявки.

  %p
    До того, как размещать запросы или предложения с помощью sms, вы должны добавить свой номер телефона
    - if logged_in?
      = link_to("в свой профиль.", profile_person_settings_path(:person_id => @current_user.id)) + "." 
    - else
      в свой профиль.
  
  %p Сообщения должны быть отправлены на номер +358400312821 и иметь следующий формат: «kassi ride offer/request origin destination time (необязательное описание)», где «offer/request» - «предложение/запрос», «origin» - «откуда», «destination» - «куда», «time» - «время». Например:
  %ul
    %li kassi ride offer улица_1 улица_2 18:30 едут двое
    %li kassi ride request вокзал_Брянск1 старый_аэропорт 14:00
  
  %p В настоящее время все части SMS разделяются с помощью пробелов, таким образом, для корректной обработки, пишите адреса без пробелов. Kassi будет осуществлять поиск по базе предложений и запросов руководствуясь местоположениями.
  
  %p Как правило, время подразумевается в пределах суток, но можно написать и точную дату, в соответствии со следующим форматом: 24.11.2011-17:30.
  
  %p 
    SMS-функционал всё ещё находится в разработке, поэтому могут возникать ошибки в его работе. Отправьте  
    = link_to "сообщение об ошибке", "#", :id => "give_feedback_link"
    если вы столкнулись с неправильной работой сервиса или у вас есть идеи по улучшению качества его работы.

app/views/infos/register_details.haml
= render :file => community_file("register_details", true)

app/views/infos/terms.haml
= render :partial => "people/help_texts/terms"